/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp4;

import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class Escritorio extends javax.swing.JFrame {

    HashSet<Alumno> alumnos = new HashSet<>();
    HashSet<Materia> materias = new HashSet<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Escritorio.class.getName());

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        JIFformAlumno = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        lblLegajo = new javax.swing.JLabel();
        txtLegajo = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        JIFformMaterias = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        btnGuardarMateria = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        JIFformInscripcion = new javax.swing.JInternalFrame();
        pnlFormInscripcion = new javax.swing.JPanel();
        txtFormInscripcion = new javax.swing.JLabel();
        txtFormInscripcionMateria = new javax.swing.JLabel();
        txtFormInscripcionAlumno = new javax.swing.JLabel();
        cmbMaterias = new javax.swing.JComboBox<>();
        cmbAlumnos = new javax.swing.JComboBox<>();
        btnFormInscripcionInscribirse = new javax.swing.JButton();
        btnFormInscripcionSalir = new javax.swing.JButton();
        JIFformInscriptos = new javax.swing.JInternalFrame();
        pnlFormInscriptos = new javax.swing.JPanel();
        cmbFormInscriptosAlumnos = new javax.swing.JComboBox<>();
        lblFormInscriptosMaterias = new javax.swing.JLabel();
        txtFormInscriptosNumMaterias = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnJIFformInscriptosSalir = new javax.swing.JButton();
        mnbPrincipal = new javax.swing.JMenuBar();
        mnuAlumno = new javax.swing.JMenu();
        mitAgregarAlumno = new javax.swing.JMenuItem();
        mnuMateria = new javax.swing.JMenu();
        mitAgregarMateria = new javax.swing.JMenuItem();
        mnuRegistro = new javax.swing.JMenu();
        mitRegistrase = new javax.swing.JMenuItem();
        mnuInscriptos = new javax.swing.JMenu();
        mitInscriptos = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mitSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JIFformAlumno.setVisible(true);

        lblLegajo.setText("Legajo");

        txtLegajo.addActionListener(this::txtLegajoActionPerformed);

        lblApellido.setText("Apellido");

        lblNombre.setText("Nombre");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido)
                    .addComponent(lblLegajo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLegajo, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLegajo)
                    .addComponent(txtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout JIFformAlumnoLayout = new javax.swing.GroupLayout(JIFformAlumno.getContentPane());
        JIFformAlumno.getContentPane().setLayout(JIFformAlumnoLayout);
        JIFformAlumnoLayout.setHorizontalGroup(
            JIFformAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFformAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JIFformAlumnoLayout.setVerticalGroup(
            JIFformAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFformAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JIFformMaterias.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de Materias ");

        jLabel4.setText("Codigo De Materia");

        txtCodigo.addActionListener(this::txtCodigoActionPerformed);

        jLabel5.setText("Nombre de la Materia");

        txtNombreMateria.addActionListener(this::txtNombreMateriaActionPerformed);

        jLabel6.setText("Año al que pertenece");

        btnGuardarMateria.setText("Guardar");
        btnGuardarMateria.addActionListener(this::btnGuardarMateriaActionPerformed);

        jButton5.setText("Nuevo");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Salir");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(273, Short.MAX_VALUE)
                        .addComponent(btnGuardarMateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNombreMateria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(txtAnio, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarMateria)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        javax.swing.GroupLayout JIFformMateriasLayout = new javax.swing.GroupLayout(JIFformMaterias.getContentPane());
        JIFformMaterias.getContentPane().setLayout(JIFformMateriasLayout);
        JIFformMateriasLayout.setHorizontalGroup(
            JIFformMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFformMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JIFformMateriasLayout.setVerticalGroup(
            JIFformMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFformMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JIFformInscripcion.setVisible(true);

        txtFormInscripcion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFormInscripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFormInscripcion.setText("Formulario de Inscripcion");

        txtFormInscripcionMateria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFormInscripcionMateria.setText("Elija una Materia");

        txtFormInscripcionAlumno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFormInscripcionAlumno.setText("Elija un Alumno");

        cmbMaterias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cmbAlumnos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnFormInscripcionInscribirse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFormInscripcionInscribirse.setText("Inscribirse");

        btnFormInscripcionSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFormInscripcionSalir.setText("Salir");
        btnFormInscripcionSalir.addActionListener(this::btnFormInscripcionSalirActionPerformed);

        javax.swing.GroupLayout pnlFormInscripcionLayout = new javax.swing.GroupLayout(pnlFormInscripcion);
        pnlFormInscripcion.setLayout(pnlFormInscripcionLayout);
        pnlFormInscripcionLayout.setHorizontalGroup(
            pnlFormInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormInscripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFormInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormInscripcionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFormInscripcionInscribirse)
                .addGap(18, 18, 18)
                .addComponent(btnFormInscripcionSalir)
                .addContainerGap())
            .addGroup(pnlFormInscripcionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlFormInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFormInscripcionMateria)
                    .addComponent(txtFormInscripcionAlumno))
                .addGap(67, 67, 67)
                .addGroup(pnlFormInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlFormInscripcionLayout.setVerticalGroup(
            pnlFormInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormInscripcionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtFormInscripcion)
                .addGap(74, 74, 74)
                .addGroup(pnlFormInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFormInscripcionMateria))
                .addGap(18, 18, 18)
                .addGroup(pnlFormInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFormInscripcionAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(pnlFormInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormInscripcionInscribirse)
                    .addComponent(btnFormInscripcionSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout JIFformInscripcionLayout = new javax.swing.GroupLayout(JIFformInscripcion.getContentPane());
        JIFformInscripcion.getContentPane().setLayout(JIFformInscripcionLayout);
        JIFformInscripcionLayout.setHorizontalGroup(
            JIFformInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFformInscripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JIFformInscripcionLayout.setVerticalGroup(
            JIFformInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFformInscripcionLayout.createSequentialGroup()
                .addComponent(pnlFormInscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JIFformInscriptos.setTitle("Formulario Inscriptos");
        JIFformInscriptos.setVisible(true);

        cmbFormInscriptosAlumnos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblFormInscriptosMaterias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFormInscriptosMaterias.setText("Materias ");

        txtFormInscriptosNumMaterias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Formulario de Inscriptos");
        jLabel2.setName(""); // NOI18N

        btnJIFformInscriptosSalir.setText("Salir");
        btnJIFformInscriptosSalir.addActionListener(this::btnJIFformInscriptosSalirActionPerformed);

        javax.swing.GroupLayout pnlFormInscriptosLayout = new javax.swing.GroupLayout(pnlFormInscriptos);
        pnlFormInscriptos.setLayout(pnlFormInscriptosLayout);
        pnlFormInscriptosLayout.setHorizontalGroup(
            pnlFormInscriptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormInscriptosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblFormInscriptosMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(txtFormInscriptosNumMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormInscriptosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormInscriptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormInscriptosLayout.createSequentialGroup()
                        .addComponent(cmbFormInscriptosAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormInscriptosLayout.createSequentialGroup()
                        .addComponent(btnJIFformInscriptosSalir)
                        .addContainerGap())))
        );
        pnlFormInscriptosLayout.setVerticalGroup(
            pnlFormInscriptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormInscriptosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addComponent(cmbFormInscriptosAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(pnlFormInscriptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormInscriptosMaterias)
                    .addComponent(txtFormInscriptosNumMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(btnJIFformInscriptosSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout JIFformInscriptosLayout = new javax.swing.GroupLayout(JIFformInscriptos.getContentPane());
        JIFformInscriptos.getContentPane().setLayout(JIFformInscriptosLayout);
        JIFformInscriptosLayout.setHorizontalGroup(
            JIFformInscriptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFformInscriptosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormInscriptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JIFformInscriptosLayout.setVerticalGroup(
            JIFformInscriptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFformInscriptosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFormInscriptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        escritorio.setLayer(JIFformAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(JIFformMaterias, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(JIFformInscripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(JIFformInscriptos, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(JIFformInscriptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JIFformAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JIFformMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JIFformInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(JIFformInscriptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JIFformAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JIFformMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(JIFformInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mnuAlumno.setText("Alumno");

        mitAgregarAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitAgregarAlumno.setText("Agregar Alumno");
        mitAgregarAlumno.addActionListener(this::mitAgregarAlumnoActionPerformed);
        mnuAlumno.add(mitAgregarAlumno);

        mnbPrincipal.add(mnuAlumno);

        mnuMateria.setText("Materia");

        mitAgregarMateria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitAgregarMateria.setText("Agregar Materia");
        mitAgregarMateria.addActionListener(this::mitAgregarMateriaActionPerformed);
        mnuMateria.add(mitAgregarMateria);

        mnbPrincipal.add(mnuMateria);

        mnuRegistro.setText("Registro");

        mitRegistrase.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mitRegistrase.setText("Registrarse");
        mitRegistrase.addActionListener(this::mitRegistraseActionPerformed);
        mnuRegistro.add(mitRegistrase);

        mnbPrincipal.add(mnuRegistro);

        mnuInscriptos.setText("Inscriptos");

        mitInscriptos.setText("Inscriptos");
        mitInscriptos.addActionListener(this::mitInscriptosActionPerformed);
        mnuInscriptos.add(mitInscriptos);

        mnbPrincipal.add(mnuInscriptos);

        mnuSalir.setText("Salir");

        mitSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        mitSalir.setText("DE VERAS?");
        mitSalir.addActionListener(this::mitSalirActionPerformed);
        mnuSalir.add(mitSalir);

        mnbPrincipal.add(mnuSalir);

        setJMenuBar(mnbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void guardarAlumno() {

        try {
            String newLegajo = txtLegajo.getText().trim();
            String newApellido = txtApellido.getText().trim();
            String newNombre = txtNombre.getText().trim();

            if (newLegajo.isEmpty() || newApellido.isEmpty() || newNombre.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Completa todos los campos",
                        "Atencion",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            int legajo = Integer.parseInt(newLegajo);
            Alumno nuevo = new Alumno(legajo, newApellido, newNombre);

            for (Alumno n : alumnos) {
                if (n.getNumLegajo() == legajo) {
                    JOptionPane.showMessageDialog(this,
                            "Ya hay un alumno con este legajo",
                            "Atencion",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

            alumnos.add(nuevo);
            JOptionPane.showMessageDialog(this,
                    "Alumno guardado exitosamente");
            limpiarCampos();
            cmbAlumnos.addItem(nuevo);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El legajo debe ser un número",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiarCampos() {
        txtLegajo.setText("");
        txtApellido.setText("");
        txtNombre.setText("");
        txtCodigo.setText("");
        txtNombreMateria.setText("");
        txtAnio.setText("");

    }

    private void guardarMateria() {
        try {
            String codigoTexto = txtCodigo.getText().trim();
            String nombre = txtNombreMateria.getText().trim();
            String anioTexto = txtAnio.getText().trim();

            if (codigoTexto.isEmpty() || nombre.isEmpty() || anioTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Complete todos los campos.", "Atención", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idMateria = Integer.parseInt(codigoTexto);
            int anio = Integer.parseInt(anioTexto);

            Materia nueva = new Materia(idMateria, nombre, anio);
            for (Materia mat : materias) {
                if (mat.getIdMateria() == idMateria) {
                    JOptionPane.showMessageDialog(this,
                            "Ya existe una materia con ese código.", "Atención", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

            materias.add(nueva);
            JOptionPane.showMessageDialog(this, "Materia guardada correctamente.");
            limpiarCampos();
            cmbMaterias.addItem(nueva);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "El código y el año deben ser numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guardarAlumno();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMateriaActionPerformed
        // TODO add your handling code here:
        guardarMateria();
    }//GEN-LAST:event_btnGuardarMateriaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtNombreMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMateriaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        JIFformAlumno.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mitSalirActionPerformed

    private void mitRegistraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitRegistraseActionPerformed
        // TODO add your handling code here:
        JIFformInscripcion.setVisible(true);
    }//GEN-LAST:event_mitRegistraseActionPerformed

    private void mitAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAgregarAlumnoActionPerformed
        // TODO add your handling code here:
        JIFformAlumno.setVisible(true);
        //escritorio.add(JIFformAlumno);
        escritorio.moveToFront(JIFformAlumno);
    }//GEN-LAST:event_mitAgregarAlumnoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JIFformAlumno.setVisible(false);
        JIFformMaterias.setVisible(false);
        JIFformInscripcion.setVisible(false);
        JIFformInscriptos.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLegajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLegajoActionPerformed

    private void mitAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAgregarMateriaActionPerformed
        // TODO add your handling code here:
        JIFformMaterias.setVisible(true);
        escritorio.moveToFront(JIFformMaterias);

    }//GEN-LAST:event_mitAgregarMateriaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JIFformMaterias.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnFormInscripcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormInscripcionSalirActionPerformed
        // TODO add your handling code here:
        JIFformInscripcion.setVisible(false);
    }//GEN-LAST:event_btnFormInscripcionSalirActionPerformed

    private void mitInscriptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitInscriptosActionPerformed
        // TODO add your handling code here:
        JIFformInscriptos.setVisible(true);
    }//GEN-LAST:event_mitInscriptosActionPerformed

    private void btnJIFformInscriptosSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJIFformInscriptosSalirActionPerformed
        // TODO add your handling code here:
        JIFformInscriptos.setVisible(false);
    }//GEN-LAST:event_btnJIFformInscriptosSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Escritorio().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame JIFformAlumno;
    private javax.swing.JInternalFrame JIFformInscripcion;
    private javax.swing.JInternalFrame JIFformInscriptos;
    private javax.swing.JInternalFrame JIFformMaterias;
    private javax.swing.JButton btnFormInscripcionInscribirse;
    private javax.swing.JButton btnFormInscripcionSalir;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarMateria;
    private javax.swing.JButton btnJIFformInscriptosSalir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Alumno> cmbAlumnos;
    private javax.swing.JComboBox<String> cmbFormInscriptosAlumnos;
    private javax.swing.JComboBox<Materia> cmbMaterias;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblFormInscriptosMaterias;
    private javax.swing.JLabel lblLegajo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JMenuItem mitAgregarAlumno;
    private javax.swing.JMenuItem mitAgregarMateria;
    private javax.swing.JMenuItem mitInscriptos;
    private javax.swing.JMenuItem mitRegistrase;
    private javax.swing.JMenuItem mitSalir;
    private javax.swing.JMenuBar mnbPrincipal;
    private javax.swing.JMenu mnuAlumno;
    private javax.swing.JMenu mnuInscriptos;
    private javax.swing.JMenu mnuMateria;
    private javax.swing.JMenu mnuRegistro;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JPanel pnlFormInscripcion;
    private javax.swing.JPanel pnlFormInscriptos;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JLabel txtFormInscripcion;
    private javax.swing.JLabel txtFormInscripcionAlumno;
    private javax.swing.JLabel txtFormInscripcionMateria;
    private javax.swing.JTextField txtFormInscriptosNumMaterias;
    private javax.swing.JTextField txtLegajo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables

}
